version: "3.9"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db

  budget-buddy:
    build: "budget-buddy/."
    restart: always
    ports:
      - 80:80
    volumes:
      - userdata:/root
      - ../budget-buddy:/var/www/html
    links:
      - adminer
      - db

volumes:
  userdata:
